# Generated by Django 5.1.7 on 2025-03-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0003_productreview_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productreview",
            name="sentiment",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
