# Generated by Django 5.1.7 on 2025-03-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0007_remove_video_title_remove_video_uploaded_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="videos/"),
        ),
    ]
