# Generated by Django 5.1.7 on 2025-03-13 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0010_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="review_images/"),
        ),
    ]
