# Generated by Django 5.1.7 on 2025-03-13 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0012_discount_order_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="valid_from",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="discount",
            name="valid_to",
            field=models.DateField(),
        ),
    ]
