version: '3'

services:
  nginx:
    image: nginx:1.22.1
    volumes:
      - ./api/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
  
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email eseeva228@gmail.com -d vasilekretsu.ru --agree-tos --no-eff-email