# volumes:
#   pg_data1:

# services:
#   db1:
#     image: postgres:13
#     env_file: .env
#     volumes:
#       - pg_data1:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   redis:
#     image: redis:7
#     restart: always
#     ports:
#       - "6379:6379"

#   backend:
#     build: /api
#     env_file: .env
#     ports:
#       - "8000:8000"
#     networks:
#       - backend_network
#     depends_on:
#       - db1
#       - redis

#   nginx:
#     build: ./api/nginx
#     env_file: .env
#     ports:
#       - "80:80"
#     networks:
#       - backend_network
#     depends_on:
#       - backend

# networks:
#   backend_network:
#     driver: bridge


###################
version: "3.2"


volumes:
  pg_data1:
  static_data:
  media_data:
  certbot_conf:    # добавьте эти две строки
  certbot_www:     # добавьте эти две строки

services:
  db1:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data1:/var/lib/postgresql/data
    networks:
      - backend_network
    expose:
      - "5432"

  redis:
    image: redis:7
    restart: always
    networks:
      - backend_network
    expose:
      - "6379"

  backend:
    build: ./api
    env_file: .env
    volumes:
      - static_data:/staticfiles
      - media_data:/media
    depends_on:
      - db1
      - redis
    environment:
      - SECRET_KEY=django-insecure-1(ny8xf!hmj6&v0kte#a!d--i&ybk7_10zd+qif!_(+d22*lhs
    networks:
      - backend_network

  nginx:
    build: ./api/nginx
    env_file: .env
    volumes:
      - static_data:/staticfiles
      - media_data:/media
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend_network
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot -w /var/www/certbot -d vasilekretsu.ru --agree-tos --no-eff-email --force-renewal --email eseeva228@gmail.com -v

networks:
  backend_network:
    driver: bridge