version: '3'

volumes:
  pg_data1:

services:
  db1:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data1:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    build: 'ihnupfidi1/backend_api'
    env_file: .env

  nginx:
    image: 'ihnupfidi1/backend_nginx'
    env_file: .env
    ports:
      - "9000:80"

