# Generated by Django 3.2.3 on 2025-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Администратор"),
                    ("user", "Пользователь"),
                    ("supplier", "Поставщик"),
                    ("employee", "Сотрудник"),
                    ("customer", "Клиент"),
                ],
                help_text="Выберите роль",
                max_length=150,
                verbose_name="Роль",
            ),
        ),
    ]
