# Generated by Django 4.2.20 on 2025-04-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_auto_20250306_2031"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="yandex_oauth_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Яндекс OAuth ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Администратор"),
                    ("user", "Пользователь"),
                    ("supplier", "Поставщик"),
                    ("employee", "Сотрудник"),
                    ("customer", "Клиент"),
                ],
                default="user",
                help_text="Выберите роль",
                max_length=150,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
