# Generated by Django 3.2.3 on 2025-03-06 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20250306_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to="users.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier",
                to="users.user",
            ),
            preserve_default=False,
        ),
    ]
