# Generated by Django 3.2.3 on 2025-03-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_supplier_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
    ]
