# Generated by Django 3.2.3 on 2025-03-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_employee_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="birdth_date",
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
