# Generated by Django 5.1.7 on 2025-03-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0002_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="sentiment",
            field=models.FloatField(default=0.0),
        ),
    ]
