# Generated by Django 5.1.7 on 2025-03-13 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0005_video_product_video_delete_productreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="api_django.video",
            ),
        ),
    ]
