# Generated by Django 5.1.7 on 2025-03-13 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_django", "0006_alter_product_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="title",
        ),
        migrations.RemoveField(
            model_name="video",
            name="uploaded_at",
        ),
    ]
