# Generated by Django 3.2.3 on 2025-02-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_django', '0004_remove_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
