# Generated by Django 3.2.24 on 2025-04-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youmoney_app', '0002_payment_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
    ]
