name: Main Docker workflow

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_docker_hub:
    name: Push backend Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./api/
          file: ./api/Dockerfile  # Указываем путь к Dockerfile явно
          push: true
          tags: ihnupfidi1/backend_api:latest

  build_nginx_and_push_to_docker_hub:
    name: Push nginx Docker image to DockerHub
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub  # Ждёт завершения сборки backend-а
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v4
        with:
          context: ./api/nginx/
          push: true
          tags: ihnupfidi1/backend_nginx:latest

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install flake8==6.0.0 flake8-isort==6.0.0 pycodestyle==2.10.0
        pip install -r ./api/requirements.txt

    - name: Test with flake8 and django tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}  # Здесь мы добавляем переменную в секцию env
      run: |
        python -m flake8 api/
        cd api/
        pytest tests/test_views.py
        pytest tests/test_urls.py
        pytest tests/test_aichat.py

